name: Daily Update Graph

on:
  schedule:
    - cron: '30 23 * * *'  # 5 AM IST
    - cron: '30 10 * * *'  # 4 PM IST
  workflow_dispatch:     # Optional: lets you run it manually

jobs:
  update-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: List files
        run: ls -R
        
      - name: Run update_graph
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          endpoint: ${{ secrets.endpoint }}
          EMBED_KEY: ${{ secrets.EMBED_KEY }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL}}
          DATABSE_URL: ${{secrets.DATABASE_URL}}
          
        run: python -m api.update_graph
